# site settings
title: Noman Ur Rehman
subtitle: Adventures of a Server Side Superhero
email: nomanurrehman@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: https://nomanurrehman.github.io
author: Noman Ur Rehman
street_address:
city:
state:
zip_code:
country:
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 5

# social settings
500px_url:
facebook_url:
github_url: https://github.com/nomanurrehman
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/nomanurrehman/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
